version: '3'

services:

  nginx:
    image: nginx:1.19.1
    container_name: nginx
    restart: always
    ports:
      - 8086:80
      - 443:443
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/website.conf
      - ./docker/storage/logs/nginx:/var/logs/nginx
    depends_on:
      - yektadgphp
    links:
      - yektadgphp

  yektadgphp:
    image: yektadgphp:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: ./Dockerfile
    container_name: yektadgphp
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    image: mysql:8.0.21
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=yektadg_db
      - MYSQL_USER=yektadg_user
      - MYSQL_PASSWORD=123456
    ports:
      - 33061:3306
    volumes:
      - ./docker/storage/mysql-data:/var/lib/mysql
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql