version: '3'

services:
  nginx:
    image: nginx:1.19.1
    container_name: nginx
    restart: always
    ports:
      - 8086:80
    networks:
      - yektadg_network
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/storage/logs/nginx:/var/logs/nginx
    depends_on:
      - yektadgphp
    links:
      - yektadgphp

  yektadgphp:
    image: yektadgphp:latest

    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: ./Dockerfile
    container_name: yektadgphp
    networks:
      - yektadg_network
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    image: mysql:8.0.21
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 33061:3306
    networks:
      - yektadg_network
    volumes:
      - ./docker/storage/mysql-data:/var/lib/mysql
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

networks:
  yektadg_network:
